# Generated by Django 2.0 on 2018-01-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0004_caregiver_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('alarm', models.BooleanField(default=True)),
            ],
        ),
    ]
