# Generated by Django 2.0 on 2018-01-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0006_reminder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caregiver',
            old_name='caregiver',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='name',
        ),
    ]
