# Generated by Django 2.0 on 2018-01-16 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diabetes', '0007_auto_20180112_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
