# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0009_auto_20180116_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
