# Generated by Django 2.0 on 2018-01-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0010_auto_20180117_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
