# Generated by Django 2.0 on 2018-01-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0011_auto_20180118_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
