# Generated by Django 2.0 on 2018-01-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0013_auto_20180122_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
